# Generated by Django 3.1.7 on 2021-03-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danh_muc',
            fields=[
                ('id_danhmuc', models.AutoField(primary_key=True, serialize=False)),
                ('Ten_danhmuc', models.CharField(max_length=50)),
                ('ngay_tao', models.DateField()),
            ],
            options={
                'db_table': 'Danh_muc',
            },
        ),
    ]
