# Generated by Django 3.1.7 on 2021-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhaPhatHanh',
            fields=[
                ('id_NPH', models.AutoField(primary_key=True, serialize=False)),
                ('Ten_NPH', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NhaPhatHanh',
            },
        ),
        migrations.CreateModel(
            name='NhaXuatBan',
            fields=[
                ('id_NXB', models.AutoField(primary_key=True, serialize=False)),
                ('Ten_NXB', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NhaXuatBan',
            },
        ),
        migrations.CreateModel(
            name='Tac_gia',
            fields=[
                ('id_tacgia', models.AutoField(primary_key=True, serialize=False)),
                ('Ten_tacgia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Tac_gia',
            },
        ),
    ]
