# Generated by Django 3.1.7 on 2021-03-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nhaphathanh_nhaxuatban_tac_gia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id_sach', models.AutoField(primary_key=True, serialize=False)),
                ('Ten_sach', models.CharField(max_length=200)),
                ('Ten_tac_gia', models.CharField(default='a', max_length=100)),
                ('id_danhmuc', models.IntegerField()),
                ('id_NXB', models.IntegerField()),
                ('id_NPH', models.IntegerField()),
                ('img_sach', models.ImageField(max_length=500, upload_to='')),
                ('gia_tien_goc', models.FloatField()),
                ('gia_tien_sale', models.FloatField()),
                ('so_luong', models.IntegerField()),
                ('mo_ta', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Ban chay'), (1, 'Het hang'), (2, 'Con hang'), (3, 'Sale off')])),
                ('ngay_tao', models.DateField()),
            ],
            options={
                'db_table': 'Sach',
            },
        ),
    ]
