# Generated by Django 3.1.7 on 2021-03-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Tag',
            fields=[
                ('id_bat', models.AutoField(primary_key=True, serialize=False)),
                ('id_sach', models.IntegerField()),
                ('id_tag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.AutoField(primary_key=True, serialize=False)),
                ('Ten_tag', models.CharField(max_length=50, null='False')),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
    ]
