# Generated by Django 3.1.7 on 2021-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_book_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_tag',
            name='id_sach',
            field=models.IntegerField(choices=[]),
        ),
        migrations.AlterField(
            model_name='book_tag',
            name='id_tag',
            field=models.IntegerField(choices=[]),
        ),
        migrations.AlterField(
            model_name='sach',
            name='id_NPH',
            field=models.IntegerField(choices=[]),
        ),
        migrations.AlterField(
            model_name='sach',
            name='id_NXB',
            field=models.IntegerField(choices=[]),
        ),
        migrations.AlterField(
            model_name='sach',
            name='id_danhmuc',
            field=models.IntegerField(choices=[]),
        ),
    ]
